version: '3'
services:
  server:
    container_name: game-server
    build: ./server
    ports:
      - "5000:5000"
  client:
    container_name: game-client
    build: ./client
    ports:
      - "3000:80"